In [1]:
import itertools
from functools import reduce
from itertools import product

import operator

K = Fields()

q = 2**61 - 1
Fq = GF(q)
x = polygen(Fq, 'x')
Fq2.<u> = Fq.extension(x^2+1)
log_n = 4
n = 2**log_n
v = vector(Fq, [Fq.random_element() for _ in range(n)])

def get_bit(n, k):
    return (n >> k) & 1

def int_to_bits(n, bit_length=None):
    if bit_length is None:
        bit_length = n.bit_length() if n != 0 else 1
    return [(n >> i) & 1 for i in range(bit_length)]

def multilinear_extension(v, F, var_names=None):
    n = len(v)
    m = n.bit_length() - 1
    if 2 ** m != n:
        raise ValueError("Vector length must be a power of 2.")
    
    if var_names is None:
        var_names = [f'X{i}' for i in range(1, m+1)]
    R = PolynomialRing(F, var_names)
    X = R.gens()
    p = R.zero()
    
    for i in range(n):
        term = F(v[i]) 
        bits = int_to_bits(i,m) 
        
        for j in range(m):
            if bits[j] == 1:
                term *= X[j]
            else:
                term *= (1 - X[j])
        p += term
    return p

v_tilde = multilinear_extension(v, Fq)

for i, t in enumerate(v):
  assert t == v_tilde([j for j in int_to_bits(i, log_n)])


def multilinear_matrix_extension(M, F, var_names=None):
    d, n = M.dimensions()
    total_elements = d * n
    
    m = total_elements.bit_length() - 1
    if 2^m != total_elements:
        raise ValueError("Matrix dimensions must multiply to a power of 2 (d * n = 2^m).")
    
    # Flatten the matrix into a vector (row-major order)
    v = M.list()
    
    if var_names is None:
        var_names = [f'X{i}' for i in range(1, m+1)]
    R = PolynomialRing(F, var_names)
    X = R.gens()
    
    p = R.zero()
    for i in range(total_elements):
        term = F(v[i])  
        bits = int_to_bits(i,m) 
        
        for j in range(m):
            if bits[j] == 1:
                term *= X[j]
            else:
                term *= (1 - X[j])
        
        p += term
    
    return p

M = Matrix(Fq, [[ Fq.random_element() for _ in range(n)] for _ in range(n)])
M_tilde = multilinear_matrix_extension(M, Fq)

for i, row in enumerate(M):
  for j, e in enumerate(row):
    assert M[i][j] == M_tilde([y for y in int_to_bits(j, log_n)]+[x for x in int_to_bits(i, log_n)])


# Build multi-linear basis polynomials
var_names = [f'X{i}' for i in range(log_n)]
R = PolynomialRing(Fq2, var_names)
X = R.gens()
print(X)
# print([X[i] for i in range(log_n)])
basis = []
for i in range(n):
    bits = [(i >> j) & 1 for j in range(log_n)]
    poly = 1
    for b, x in zip(bits, [X[i] for i in range(log_n)]):
        poly *= x if b else (1 - x)
    basis.append(poly)

# print(basis)

tilde_f_r = sum(v[i] * basis[i] for i in range(n))
v_tilde2 = multilinear_extension(v, Fq2)
for i, t in enumerate(v):
  params = [j for j in int_to_bits(i, log_n)]
  assert tilde_f_r(params) == v_tilde(params)


(X0, X1, X2, X3)


In [2]:
# 2.3 Rings and Modules
eta = 81
d = 54
q = 2**61 - 1
Fq = GF(q)
x = polygen(Fq, 'x')
Phi = x ** 54 + x ** 27 + 1
Rq.<u> = Fq.extension(Phi)
kappa = 16
## m = 2 ** 22 # TOO MUCH MEMORY
#m = 2 ** 8 # for testing purposes
#M = random_matrix(Rq, kappa, m)
a = Rq.random_element()

def cf(a):
    return a.list()

def cf_inv(a):
    return Rq(a)

def shift_matrix(Fq, Phi, d):
    F = matrix(Fq, d, d)
    c = cf(Phi)
    for i in range(d):
        for j in range(d):
            if i - 1 == j:
                F[i, j] = 1
            if j == d - 1:
                F[i, j] = -c[i]
    return F

def rot(a, Phi, Fq):
    cf_a = vector(Fq, a if isinstance(a, list) else cf(a))
    d = len(cf_a)
    F = shift_matrix(Fq, Phi, d)

    columns = [cf_a]
    F_power = F  # Start with F^1
    for _ in range(1, d):
        current = F_power * cf_a
        columns.append(current)
        F_power = F_power * F  # Compute next power incrementally
    rows = list(zip(*columns))
    M = matrix(Fq, len(cf_a), len(cf_a), sum([list(row) for row in rows], []))

    return M    # print([(F**i) * cf_a for i in range(1, d)])
    
# print(shift_matrix(Fq, Phi, d))
rot_a = rot(a, Phi, Fq)
b = Rq.random_element()
assert rot_a * vector(Fq, cf(b)) == vector(Fq,cf(a*b))

# F7 = GF(7)

# y = polygen(F7, 'y')
# Phi_test = y ** 3 + 1
# R7.<u> = F7.extension(Phi_test)

# a = 4*u**2 + 2*u + 3
# rot_a = rot(a, Phi_test, F7)
# print(rot_a)
# b = u**2 + 1
# print("cf(a*b)", cf(a*b))
# print("rot_a * vector(F7, cf(b)", rot_a * vector(F7, cf(b)))
# assert rot_a * vector(F7, cf(b)) == vector(F7, cf(a*b))

# 3.2 Neo’s solution, part-1: A matrix commitment scheme

def embed_Fq_to_Rq(z_i, d):
    """
    Embed a field element z_i ∈ Fq into Rq by using its bits
    as coefficients of a polynomial in Rq.
    """
    z_int = int(z_i)
    bits = [((z_int >> i) & 1) for i in range(d)]
    poly = sum(Fq(bits[i]) * u^i for i in range(len(bits)))
    return Rq(poly)

z_i = Fq.random_element()
z_i_embedded = embed_Fq_to_Rq(z_i, d)

print(f"Original Fq element: {z_i}")
print(f"Embedded Rq element: {z_i_embedded}")


Original Fq element: 738799067981873711
Embedded Rq element: u^47 + u^45 + u^44 + u^43 + u^42 + u^40 + u^39 + u^38 + u^36 + u^34 + u^33 + u^31 + u^26 + u^25 + u^24 + u^22 + u^21 + u^20 + u^17 + u^16 + u^9 + u^5 + u^3 + u^2 + u + 1


In [3]:
from random import randint


def decomp_b(z, d=None):
    F = z.base_ring()
    m = len(z)
    b = 2

    # Determine degree if not provided
    if d is None:
        # Find smallest d such that b^d > max(z)
        max_val = max([abs(int(zi)) for zi in z])
        d = 1
        while b**d <= max_val:
            d += 1

    # Initialize the result matrix
    # Z = matrix(F, d, m)

    # Perform b-ary decomposition
    cols = []
    for j in range(m):
        value = int(z[j])
        bits = [((value >> i) & 1) for i in range(d)]
        cols.append(bits)
    rows = list(zip(*cols))
    Z = matrix(F, d, m, sum([list(row) for row in rows], []))

    return Z


z_1 = Fq(123)
z_2 = Fq(567)
z_3 = Fq(890)
m = 3
z_1_embedded = embed_Fq_to_Rq(z_1, d)
z_2_embedded = embed_Fq_to_Rq(z_2, d)
z_3_embedded = embed_Fq_to_Rq(z_3, d)
z_vec = vector(Fq, [z_1, z_2, z_3])
print(z_vec)
Z = decomp_b(z_vec, d)
print("len(cf(z_1_embedded))", len(cf(z_1_embedded)))
print("len([Z[i, 0] for i in range(d)])", len([Z[i, 0] for i in range(d)]))
assert cf(z_1_embedded) == [Z[i, 0] for i in range(d)]
assert cf(z_2_embedded) == [Z[i, 1] for i in range(d)]
assert cf(z_3_embedded) == [Z[i, 2] for i in range(d)]

print("check sum", [Fq(sum([2**i * Z[i, col] for i in range(d)])) for col in range(m)])
assert list(z_vec) == [
    Fq(sum([2**i * Z[i, col] for i in range(d)])) for col in range(m)
]


def split_b(Z, k=None):
    F = Z.base_ring()
    d, m = Z.dimensions()
    b = 2

    # Determine depth if not provided
    if k is None:
        # Find smallest k such that b^k > max(Z)
        max_val = max([abs(int(Z[i, j])) for i in range(d) for j in range(m)])
        k = 1
        while b**k <= max_val:
            k += 1
    # Initialize the result matrices
    result = [matrix(F, d, m) for _ in range(k)]

    # Perform b-ary decomposition
    for i in range(d):
        for j in range(m):
            value = int(Z[i, j])
            bits = [((value >> i) & 1) for i in range(k)]
            for l in range(k):
                result[l][i, j] = F(bits[l])
    return result


max_val = 2**20  # low norm
test = matrix(Fq, d, m)
for i in range(d):
    for j in range(m):
        test[i, j] = Fq(randint(0, max_val - 1))
Z = split_b(test)
Z_restored = matrix(Fq, d, m)
for i, z in enumerate(Z):
    Z_restored += (2**i) * z

print(Z_restored)
assert test == Z_restored

(123, 567, 890)
len(cf(z_1_embedded)) 54
len([Z[i, 0] for i in range(d)]) 54
check sum [123, 567, 890]
[ 626935  940415  688744]
[ 971994  709268  591859]
[  36743  452582   50093]
[ 744103  712102  715999]
[ 570149  564842  149571]
[ 272501 1018424  438848]
[ 778348  701196  878695]
[ 147013  579210   75857]
[ 171469   49429  330829]
[ 712276  875491  145234]
[ 990520  422522  898670]
[ 895454  163826  768214]
[ 160771  745826  323688]
[ 899678  555903   87393]
[ 379342 1004790  485185]
[ 107258  541776  807652]
[ 743854  417008   57209]
[ 907199  703913  428721]
[ 188195  543032  878827]
[ 849800  578594  862805]
[  50230  342838  887235]
[ 244627  868837  459627]
[ 518581  730352  766279]
[ 802479  293438 1030674]
[ 958442  558420  360732]
[ 618542  464032  832650]
[ 595884  457884  204737]
[ 843158  273358  306162]
[ 243550    3086   42524]
[ 935631  125391  840988]
[ 551030  971594  430047]
[ 740821   76978  781392]
[ 970271  891240  424775]
[ 207146  117812  651382]
[ 750486  774

In [6]:
import json

with open("../mimc_r1cs_transformed.json", "r") as f:
    r1cs = json.load(f)

# "Without loss of generality, assume that m = n and n, d · n are both powers of two"

z = vector(Fq, [int(w, base=16) for w in r1cs["witness"]])
m = len(z)
if m & (m - 1) != 0:
    next_pow2 = 1 << int(m - 1).bit_length()
    print("next_pow2", next_pow2)
    z = vector(Fq, list(z) + [0] * (next_pow2 - m))
    m = len(z)
    print("m", m)


Z = decomp_b(z, d)
print(Z.dimensions()[0])
assert d == Z.dimensions()[0]
m = Z.dimensions()[1]
print("Z.dimensions()", Z.dimensions())
for i in range(Z.nrows()):
    for j in range(Z.ncols()):
        assert Z[i, j] != 0 or Z[i, j] != 1

# In particular, each column of a low-norm matrix gets mapped as the coefficients of a single ring element.
z_prime = vector(Rq, [cf_inv(list(Z.column(j))) for j in range(Z.ncols())])
print(type(z_prime))
pp = random_matrix(Rq, kappa, m)
print("pp.dimensions()", pp.dimensions())
print("type(pp)", type(pp))
print("z_prime", type(z_prime))
c = pp * z_prime

rows = []
for x in c:
    rows.append(cf(x))
C = matrix(Fq, kappa, d, sum([list(row) for row in rows], [])).transpose()
print("C.dimensions()", C.dimensions())

next_pow2 8192
m 8192


54
Z.dimensions() (54, 8192)
<class 'sage.modules.free_module_element.FreeModuleElement_generic_dense'>
pp.dimensions() (16, 8192)
type(pp) <class 'sage.matrix.matrix_generic_dense.Matrix_generic_dense'>
z_prime <class 'sage.modules.free_module_element.FreeModuleElement_generic_dense'>
C.dimensions() (54, 16)


In [ ]:
# CCS Reduction (ΠCCS).
# This reduction takes a new MCS(b,L) instance (your new computation) and k-1 existing ME(b,L) claims, reducing them to k new ME(b,L) claims
k = 12
T = 216
### Definition 17 (Matrix constraint system relation).


# "Without loss of generality, assume that m = n and n, d · m are both powers of two"
def extend_matrix(M, size):
    rows, cols = M.dimensions()

    # Check that size is sufficient for the matrix
    if size < rows or size < cols:
        raise ValueError(
            f"Target size {size} is too small for matrix with dimensions {rows}x{cols}"
        )

    # If the matrix already has the target dimensions, return it
    if rows == cols == size:
        return M

    # Create a new square matrix of zeros with the target size
    result = matrix(M.base_ring(), size, size)

    # Copy the original matrix into the top-left corner
    for i in range(rows):
        for j in range(cols):
            result[i, j] = M[i, j]

    return result


# check r1cs constraint
A = matrix(Fq, r1cs["A"])
B = matrix(Fq, r1cs["B"])
C = matrix(Fq, r1cs["C"])
x = vector(Fq, [int(w, base=16) for w in r1cs["witness"]])
print([int(w, base=16) for w in r1cs["witness"]])
print(vector(Fq, [int(w, base=16) for w in r1cs["witness"]]))
M0x = A * x
M1x = B * x
M2x = C * x
print(M0x)
print(M1x)
print(M2x)
hadamard = vector(Fq, [u * v for u, v in zip(M0x, M1x)])
print(hadamard)
assert hadamard == M2x, f"R1CS failed: {hadamard} != {M2x}"
print("R1CS constraints are satisfied!")

M0 = extend_matrix(A, m)
M1 = extend_matrix(B, m)
M2 = extend_matrix(C, m)


print("M0.dimensions()", M0.dimensions())
print("M1.dimensions()", M1.dimensions())
print("M2.dimensions()", M2.dimensions())
print("len(z)", len(z))

M0z = M0 * z
M1z = M1 * z
M2z = M2 * z
print("len(M0z)", len(M0z))


M0z_tilde = multilinear_extension(M0z, Fq2)
M1z_tilde = multilinear_extension(M1z, Fq2)
M2z_tilde = multilinear_extension(M2z, Fq2)
# Check if R1CS constraint holds: (A·z) ⊙ (B·z) = C·z
hadamard_product = vector(Fq, [M0z[i] * M1z[i] for i in range(len(M0z))])
print(hadamard_product)
print(M2z)
# Check if the constraint is satisfied
constraint_satisfied = hadamard_product == M2z
print("constraint_satisfied", constraint_satisfied)
F = M0z_tilde * M1z_tilde - M2z_tilde

bit_combinations = list(product([0, 1], repeat=7))

# Check that F is vanishing over the hypercube
results = []
for bits in bit_combinations:
    assert F(*bits) == 0

[1, 16962, 291, 297666009, 5135631653277, 697752928138523193, 849167406662001770, 2178581182481407061, 977741101584308810, 267852404738050137, 1180532892304343208, 1489186095014854436, 1648631736550786135, 2037432786460050864, 383059035789091940, 552819801427238332, 2089881896903384247, 858774838060378177, 2187964363972031921, 1409938796371083842, 442305400501840113, 277142179060368509, 1443765647546434267, 2204190414091762292, 1333980151435638778, 700125449806104219, 2295534395802234517, 2054849951012015577, 420828435710968544, 920971504407103410, 1619561746000331692, 281971824938897587, 1422796364557301903, 2196144742125142831, 46858031604318483, 674616983589418187, 585567455048470400, 1328403894487281106, 1291346003948974312, 206324075255959495, 1099818545616623063, 2302003803086836348, 327180306461819636, 358966847420518356, 992511049737581224, 1184892677047576553, 794669624546506828, 998928196107724802, 389193302287197977, 433075601378807831, 1768387450056716093, 25505325059412570

In [ ]:
## Definition 18 (Matrix evaluation relation).


class S_R1CS:
    def __init__(self, Fq2, A, B, C):
        self.M = [A, B, C]
        self.M_tilde = [multilinear_extension(m, Fq2) for m in self.M]
        self.f = M_tilde[0] * M_tilde[1] - M_tilde[2]


class ME:

    def __init__(self, Fq, Rq, s, d, kappa):
        self.s = s
        self.d = d
        self.kappa = kappa
        self.Fq = Fq
        self.Rq = Rq
        self.pp = None

    def commit(self, z):

        self.z = z

        # "Without loss of generality, assume that m = n and n, d · n are both powers of two"
        m = len(z)
        if m & (m - 1) != 0:
            next_pow2 = 1 << int(m - 1).bit_length()
            z = vector(self.Fq, list(z) + [0] * (next_pow2 - m))
            m = len(z)
        self.m = m
        if not self.pp:
            self.pp = random_matrix(self.Rq, self.kappa, self.m)

        self.Z = decomp_b(z, d=self.d)
        assert self.d == self.Z.dimensions()[0]
        for i in range(self.Z.nrows()):
            for j in range(self.Z.ncols()):
                assert self.Z[i, j] != 0 or self.Z[i, j] != 1

        # Each column of a low-norm matrix gets mapped as the coefficients of a single ring element.
        z_prime = vector(
            self.Rq, [cf_inv(list(self.Z.column(j))) for j in range(self.Z.ncols())]
        )

        self.c = self.pp * z_prime
        rows = []
        for x in self.c:
            rows.append(cf(x))
        self.C = matrix(
            self.Fq, self.kappa, self.d, sum([list(row) for row in rows], [])
        ).transpose()


me = ME(Fq, Rq, None, d, kappa)
me.commit(z)
assert C == me.C

NameError: name 'C' is not defined